apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- deployment.yaml
- metis-ui-service.yaml
- ingress.yaml
- hpa.yaml
configMapGenerator:
- name: metis-ui-nginx-conf-production
  files:
  - nginx.conf
secretGenerator:
- name: metis-ui-environment-production
  envs:
  - env_file
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated
