language: node_js

node_js:
- 14.3.0

cache:
  directories:
  - ~/.npm
  - ~/.cache

addons:
  apt:
    packages:
    - libgconf-2-4

before_install:
- export TZ=Europe/Amsterdam

before_script:
- cp projects/metis/src/environments/apisettings-test.ts projects/metis/src/environments/apisettings.ts
- cp projects/sandbox/src/environments/apisettings-ci.ts projects/sandbox/src/environments/apisettings.ts
- npm run dist-shared
- npm install --save-optional projects/shared
