language: node_js

node_js:
- 14.3.0

cache:
  directories:
  - ~/.npm
  - ~/.cache

addons:
  apt:
    packages:
    - libgconf-2-4

before_install:
- export TZ=Europe/Amsterdam

before_script:
- cp src/environments/apisettings-test.ts src/environments/apisettings.ts
