sonar.host.url=https://sonarcloud.io
sonar.organization=europeana
sonar.projectKey=europeana_metis-ui
sonar.ws.timeout=300

# Fixed relative folder patterns for your monorepo layout
sonar.sources=projects/metis/src/app,projects/sandbox/src/app,projects/shared/src/lib
sonar.tests=projects/metis,projects/sandbox,projects/shared
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=./sonar-reports/lcov.info
