# Monorepo Structure Configuration
sonar.sources=projects
sonar.inclusions=metis/src/app/**/*,sandbox/src/app/**/*,shared/src/lib/**/*
sonar.exclusions=**/src/**/_mocked/**
sonar.test.inclusions=**/*.spec.ts

# Coverage Tracking Targets
sonar.javascript.lcov.reportPaths=sonar-reports/metis/lcov.info,sonar-reports/sandbox/lcov.info,sonar-reports/shared/lcov.info
sonar.scm.exclusions.disabled=true
sonar.ws.timeout=300
