apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sandbox-ui-ingress-acceptance
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sandbox-ui-service-acceptance
                port:
                  number: 8080
