export const isoLanguageNames: { [key: string]: string } = {
  SQ: 'Albanian',
  AR: 'Arabic',
  HY: 'Armenian',
  AZ: 'Azerbaijani',
  EU: 'Basque',
  BE: 'Belarusian',
  BS: 'Bosnian',
  BG: 'Bulgarian',
  CA: 'Catalan',
  ZH: 'Chinese',
  HR: 'Croatian (hrvatski jezik)',
  CS: 'Czech',
  DA: 'Danish',
  NL: 'Dutch',
  EN: 'English',
  ET: 'Estonian',
  FI: 'Finnish',
  FR: 'French',
  GD: 'Gaelic (Scottish)',
  GL: 'Galician',
  KA: 'Georgian',
  DE: 'German',
  EL: 'Greek',
  HE: 'Hebrew',
  HI: 'Hindi',
  HU: 'Hungarian',
  IS: 'Icelandic',
  IE: 'Interlingue',
  GA: 'Irish',
  IT: 'Italian',
  JA: 'Japanese',
  KO: 'Korean',
  LV: 'Latvian (Lettish)',
  LT: 'Lithuanian',
  MK: 'Macedonian',
  MT: 'Maltese',
  MUL: 'Multilingual Content',
  NO: 'Norwegian',
  PL: 'Polish',
  PT: 'Portuguese',
  RO: 'Romanian',
  RU: 'Russian',
  SR: 'Serbian',
  SK: 'Slovak',
  SL: 'Slovenian',
  ES: 'Spanish',
  SV: 'Swedish',
  TR: 'Turkish',
  UK: 'Ukrainian',
  CY: 'Welsh',
  YI: 'Yiddish'
};

export const isoLanguageCodes: { [key: string]: string } = Object.entries(isoLanguageNames).reduce(
  (obj, item) => {
    obj[item[1]] = item[0];
    return obj;
  },
  {} as { [key: string]: string }
);

export const isoCountryCodes: { [key: string]: string } = {
  Austria: 'AT',
  Australia: 'AU',
  Azerbaijan: 'AZ',
  Belgium: 'BE',
  Bulgaria: 'BG',
  'Bosnia and Herzegovina': 'BA',
  Belarus: 'BY',
  Canada: 'CA',
  China: 'CN',
  Russia: 'RU',
  Serbia: 'RS',
  Romania: 'RO',
  Greece: 'GR',
  Georgia: 'GE',
  'United Kingdom': 'GB',
  Croatia: 'HR',
  Hungary: 'HU',
  Lebanon: 'LB',
  Portugal: 'PT',
  Poland: 'PL',
  Estonia: 'EE',
  India: 'IN',
  Italy: 'IT',
  Japan: 'JP',
  Kazakhstan: 'KZ',
  'Korea, Republic of': 'KR',
  'San Marino': 'SM',
  Spain: 'ES',
  Montenegro: 'ME',
  Moldova: 'MD',
  Monaco: 'MC',
  'North Macedonia': 'MK',
  Malta: 'MT',
  France: 'FR',
  Finland: 'FI',
  'Faroe Islands': 'FO',
  Netherlands: 'NL',
  Norway: 'NO',
  Kosovo: 'XK',
  Switzerland: 'CH',
  'Czech Republic': 'CZ',
  Czechia: 'CZ',
  Cyprus: 'CY',
  Slovakia: 'SK',
  Slovenia: 'SI',
  Sweden: 'SE',
  Denmark: 'DK',
  Germany: 'DE',
  'United States of America': 'US',
  Turkey: 'TR',
  Liechtenstein: 'LI',
  Latvia: 'LV',
  Lithuania: 'LT',
  Luxembourg: 'LU',
  'Holy See (Vatican City State)': 'VA',
  Andorra: 'AD',
  Iceland: 'IS',
  Israel: 'IL',
  Albania: 'AL',
  Armenia: 'AM',
  Ireland: 'IE',
  Ukraine: 'UA',
  Europe: 'EU'
};

export const isoCountryNames: { [key: string]: string } = Object.entries(isoCountryCodes).reduce(
  (obj, item) => {
    obj[item[1]] = item[0];
    return obj;
  },
  {} as { [key: string]: string }
);
