apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: metis-sandbox-ui-hpa-production
spec:
  maxReplicas: #{MAX_REPLICAS}#
  minReplicas: #{MIN_REPLICAS}#
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: metis-sandbox-ui-deployment-production
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: #{UTILISATION_AVERAGE_PERCENT}#
