apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metis-sandbox-ui-ingress-production
spec:
  ingressClassName: public-iks-k8s-nginx
  tls:
    - hosts:
        - metis-sandbox.europeana.eu
      secretName: europeana.eu
  rules:
    - host: metis-sandbox.europeana.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: metis-sandbox-ui-service-production
                port:
                  number: 8080
