export enum PluginType {
  HTTP_HARVEST = 'HTTP_HARVEST',
  OAIPMH_HARVEST = 'OAIPMH_HARVEST',
  VALIDATION_EXTERNAL = 'VALIDATION_EXTERNAL',
  TRANSFORMATION = 'TRANSFORMATION',
  VALIDATION_INTERNAL = 'VALIDATION_INTERNAL',
  NORMALIZATION = 'NORMALIZATION',
  ENRICHMENT = 'ENRICHMENT',
  MEDIA_PROCESS = 'MEDIA_PROCESS',
  PREVIEW = 'PREVIEW',
  PUBLISH = 'PUBLISH',
  DEPUBLISH = 'DEPUBLISH',
  LINK_CHECKING = 'LINK_CHECKING'
}

export enum ProtocolType {
  ZIP_UPLOAD = 'ZIP_UPLOAD',
  HTTP_HARVEST = 'HTTP_HARVEST',
  OAIPMH_HARVEST = 'OAIPMH_HARVEST'
}
