export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
  accountrole: 'Account role',
  addworkflow: 'Add workflow info',
  all: 'All',
  allexecutions: 'All executions',
  allworkflows: 'All workflows',
  cancel: 'Cancel',
  cancelareyousure: 'Are you sure you want to cancel?',
  cancelling: 'Cancelling',
  changepassword: 'Change password',
  chooseworkflow: 'Choose workflow to preview',
  country: 'Country',
  create: 'Create',
  'create dataset': 'Create a dataset first',
  createdby: 'Created by',
  creating: 'Creating',
  currentworkflow: 'Current workflow',
  customxslt: 'Custom XSLT',
  dashboard: 'Dashboard',
  datestarted: 'Workflow started on',
  datecreated: 'Date Created',
  dataprovider: 'Data Provider',
  dataset: 'Dataset',
  datasetinformation: 'Dataset Information',
  datasetname: 'Dataset Name',
  datasetnamevalidator: 'Only a to z (lower and uppercase), numbers and underscores are allowed.',
  datasetsaved: 'The dataset has been saved.',
  dateupdated: 'Date Updated',
  description: 'Description',
  doubleclicktocopy: 'Double click to copy ids',
  edit: 'Edit',
  email: 'Email',
  emailerror: 'Please enter a valid email address',
  enddate: 'End date',
  enrichment: 'Enrich',
  errorharvestparameters: 'Parameters are not allowed',
  errorharvesturl: 'This is not a valid URL',
  expand: 'Expand info',
  favoritedatasets: 'Favorite datasets',
  fieldrequired: 'This field is required',
  firstname: 'First name',
  firstpublished: 'First published',
  formerror: 'Please check the form for errors.',
  ftppassword: 'FTP/HTTP password',
  ftpuser: 'FTP/HTTP user',
  fullhistory: 'See full processing history',
  generalinfo: 'General info',
  gotomapping: 'Go back to Mapping',
  harvestprotocol: 'Harvest protocol',
  harvesturl: 'Harvest URL',
  history: 'History',
  http: 'HTTP',
  identifier: 'Identifier',
  import: 'Import',
  intermediateprovider: 'Intermediate Provider',
  language: 'Language',
  lastaction: 'Last action',
  lastharvest: 'Last date of harvest',
  lastname: 'Last name',
  lastmodified: 'Last updated',
  lastpublished: 'Last published',
  loadmore: 'Load more',
  log: 'Log',
  mapping: 'Mapping',
  mediaservice: 'Process Media',
  metadataformat: 'Metadata format',
  msgbadcredentials: 'Email or password is incorrect, please try again.',
  myprofile: 'My profile',
  networkmember: 'Europeana Network Association Member',
  'new dataset': 'New dataset',
  'new organization': 'New organization',
  'next action': 'Next action',
  no: 'No',
  normalize: 'Normalise',
  nologs: 'No logs found (yet)',
  nosample: 'No sample available yet, try using the filter',
  notes: 'Notes',
  notpublished: 'Not published yet',
  numberharvested: 'Number of items harvested',
  numberpublished: 'Number of items published',
  oai: 'OAI PMH',
  ongoingexecutions: 'Ongoing executions',
  organization: 'Organization',
  overallprogress: 'Overall Progress',
  password: 'Password',
  passworderror: 'Please enter a valid password',
  passwordmatcherror: 'Passwords do not match',
  passwordnew: 'New password',
  passwordold: 'Old password',
  passwordolderror: 'The new password cannot be the same as the old password',
  passwordweakerror: 'Password is too weak',
  plugin: 'Plugin',
  preview: 'Preview',
  processinghistory: 'Processing history',
  provider: 'Provider',
  rawxml: 'Raw XML',
  recordxpath: 'Record XPath',
  refresh: 'Refresh',
  register: 'Register to Metis',
  registererror: "Your account doesn't exist or is not ready yet",
  registerinorderto: 'In order to register, please fill in the form at',
  registrationalready: 'You are already registered, you will be redirected to the sign in page!',
  registrationfailed: 'Registration failed, try again later',
  registrationsuccessful: 'Registration successful, you will be redirected to the sign in page!',
  replacedby: 'Replaced by',
  replaces: 'Replaces',
  report: 'Report',
  required: 'Required',
  restart: 'Restart',
  'run workflow': 'Run workflow',
  runaction: 'Run specific action',
  save: 'Save',
  saving: 'Saving',
  search: 'Search',
  setspec: 'Setspec',
  signin: 'Sign in',
  signintometis: 'Sign in to Metis',
  signout: 'Sign out',
  showrandom: 'Show random',
  showworkflow: 'Show workflow',
  startdate: 'Start date',
  'start workflow': 'Start your next workflow!',
  starting: 'Starting',
  startingworkflow: 'Starting workflow...',
  statistics: 'Statistics',
  status: 'Status',
  step: 'step',
  submit: 'Submit',
  totaldataset: 'Total records',
  totalprocessed: 'Total processed',
  transformation: 'Transform',
  unknown: 'Unknown',
  update: 'Update',
  updateprofile: 'If you want to update your profile, send an email to',
  url: 'URL',
  user: 'User',
  userprofile: 'User profile',
  'validation external': 'Validate External',
  'validation internal': 'Validate Internal',
  viewpreview: 'View in Preview',
  viewall: 'View all',
  viewcollections: 'View in Collections',
  workflow: 'Workflow',
  workflowcreated: 'Workflow created on',
  workflowrunning: 'The workflow is already running.',
  'workflow step': 'Workflow step',
  workflowsave: 'You have made changes to the workflow. You must save it before you can run it.',
  workflowsavenew: 'Configure the workflow steps and click the "Save" button to create a workflow.',
  workflowsaved: 'The workflow has been saved.',
  xsltaskloaddefault:
    'This dataset has no custom XSLT. Do you want to load a default XSLT for editing?',
  xsltcards: 'View per field',
  xsltcustom: 'Custom XSLT',
  xsltfull: 'View in one sheet',
  xsltinitdefault: 'Initialize editor with default XSLT',
  xsltloadcustom: 'load custom XSLT',
  xsltloaddefault: 'load default XSLT',
  xsltloading: 'Loading XSLT...',
  xsltresetdefault: 'Reset to default XSLT',
  xsltreloadcustom: 'Reload custom XSLT',
  xsltsave: 'Save XSLT',
  xsltsuccessful: 'XSLT changes have been saved successfully as custom XSLT',
  xslttryoutdefault: 'Try out with default XSLT',
  xslttryout: 'Save XSLT & Try it out',
  yes: 'Yes',
  zoho: 'Go to Zoho',
};
