export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
  'accountrole': 'Account role',
  'all': 'All',
  'allexecutions': 'All executions', 
  'allworkflows': 'All workflows', 
  'cancel': 'Cancel',
  'cancelling': 'Cancelling',
  'changepassword': 'Change password',
  'chooseworkflow': 'Choose workflow to preview',
  'country': 'Country',
  'create dataset': 'Create a dataset first',
  'createdby': 'Created by',
  'customxslt': 'Custom XSLT',
  'dashboard': 'Dashboard',
  'datestarted': 'Date started',
  'datecreated': 'Date Created',
  'dataprovider': 'Data Provider',
  'dataset': 'Dataset',
  'datasetinformation': 'Dataset Information',
  'datasetname': 'Dataset Name',
  'datasetnamevalidator': 'Only a to z (lower and uppercase), numbers and underscores are allowed.',
  'dateupdated': 'Date Updated',
  'description': 'Description',
  'email': 'Email',
  'emailerror': 'Please enter a valid email address',  
  'enddate': 'End date',  
  'enrichment': 'Enrich', 
  'expand': 'Expand info',
  'firstname': 'First name',
  'firstpublished': 'First published',
  'ftppassword': 'FTP/HTTP password',
  'ftpuser': 'FTP/HTTP user',
  'fullhistory': 'See full processing history',
  'generalinfo': 'General info',
  'gotomapping': 'Go back to Mapping',
  'harvestprotocol': 'Harvest protocol',
  'harvesturl': 'Harvest URL',
  'history': 'History',
  'http': 'HTTP',
  'identifier': 'Identifier',
  'import': 'Import',
  'intermediateprovider': 'Intermediate Provider',
  'language': 'Language', 
  'lastaction': 'Last action',
  'lastharvest': 'Last date of harvest',
  'lastname': 'Last name',
  'lastmodified': 'Last updated',
  'lastpublished': 'Last published',
  'loadmore': 'Load more',
  'log': 'Log',
  'login': 'Log in',
  'logout': 'Log out',
  'mapping': 'Mapping',
  'metadataformat': 'Metadata format',
  'myprofile': 'My profile',
  'networkmember': 'Europeana Network Association Member',
  'new dataset': 'New dataset',
  'new organization': 'New organization',
  'next action': 'Next action',
  'nosample': 'No sample available yet, try using the filter',
  'notes': 'Notes', 
  'notpublished': 'Not published yet',
  'numberharvested': 'Number of items harvested',
  'numberpublished': 'Number of items published',
  'oai': 'OAI PMH',
  'ongoingexecutions': 'Ongoing executions',
  'organization': 'Organization',
  'password': 'Password',
  'passworderror': 'Please enter a valid password',
  'passwordmatcherror': 'Password do not match',
  'passwordweakerror': 'Password is too weak',
  'plugin': 'Plugin',
  'preview': 'Preview',
  'processinghistory': 'Processing history',
  'provider': 'Provider',
  'rawxml': 'Raw XML',
  'recordxpath': 'Record XPath',
  'refresh': 'Refresh',
  'register': 'Register to Metis',
  'registererror': 'Your account doesn\'t exist or is not ready yet',
  'registerinorderto': 'In order to register, please fill in the form at',
  'registrationalready': 'You are already registered, you will be redirected to the login page!',
  'registrationfailed': 'Registration failed, try again later',
  'registrationsuccessful': 'Registration successful, you will be redirected to the login page!',
  'replacedby': 'Replaced by',
  'replaces': 'Replaces',
  'report': 'Report',
  'restart': 'Restart',
  'run workflow': 'Run workflow',
  'save': 'Save',
  'search': 'Search',
  'setspec': 'Setspec',
  'signin': 'Sign in',
  'signintometis': 'Sign in to Metis',
  'showrandom': 'Show random',
  'startdate': 'Start date',
  'start workflow': 'Start your next workflow!',
  'statistics': 'Statistics',
  'status': 'Status',
  'submit': 'Submit',
  'totaldataset': 'Total dataset',
  'totalprocessed': 'Total processed',
  'transformation': 'Transform',
  'unknown': 'Unknown',
  'update': 'Update',
  'updateprofile': 'If you want to update your profile, send an email to',
  'url': 'URL',
  'user': 'User',
  'userprofile': 'User profile',
  'validation external': 'Validate External',
  'validation internal': 'Validate Internal',
  'viewacceptance': 'View in acceptance',
  'viewall': 'View all',
  'viewcollections': 'View in collections',
  'workflow': 'Workflow',
  'workflow step': 'Workflow step',
  'xsltcards': 'View per field',
  'xsltfull': 'View in one sheet',
  'xsltloadcustom': 'load custom XSLT',
  'xsltloaddefault': 'load default XSLT',
  'xsltsave': 'Save XSLT',
  'xsltsuccessful': 'XSLT changes have been saved successfully as custom XSLT',
  'xslttryout': 'Save XSLT & Try it out',
  'zoho': 'Go to Zoho'
};