name: '* CI'
on:
  push:
    branches: [ main, develop ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  run-unit:
    name: 'tests'
    uses: ./.github/workflows/run-tests.yaml
    secrets: inherit

  run-sonar:
    needs: [run-unit]
    uses: europeana/metis-ui/.github/workflows/run-sonar.yaml@main
    secrets: inherit
    with:
      pr_number: ${{ github.event.pull_request.number || '' }}
      pr_head_ref: ${{ github.event.pull_request.head.ref || '' }}
      pr_base_ref: ${{ github.event.pull_request.base.ref || '' }}

  run-e2e:
    name: 'e2e'
    uses: ./.github/workflows/run-tests-e2e.yaml
    secrets: inherit
