name: CI
on:
  push
jobs:
  run-unit:
    name: 'tests'
    uses: ./.github/workflows/run-tests.yaml
    secrets: inherit
  run-sonar:
    needs: [run-unit]
    uses: ./.github/workflows/run-sonar.yaml
    secrets: inherit
