name: '- helper (image deployment)'
on: workflow_call
jobs:
  deploy-image:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - uses: actions/checkout@v4

      - name: Get Env File
        uses: actions/download-artifact@master
        with:
          name: envFile
          path: env_file

      - run: |
          mv env_file/env_file deployment/${{ github.event.inputs.deploy_environment }}

      - run: |
          tag=${{ github.event.inputs.tag_name || 'develop' }}
          TAG_ESCAPED=${tag//[\/]/_}
          echo TAG_ESCAPED=${TAG_ESCAPED} >> $GITHUB_ENV

      - name: Inject Variables 1
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          files: '["deployment/${{ github.event.inputs.deploy_environment }}/*.yaml"]'
        env:
          APP_IMAGE: europeana/statistics-dashboard:${{ env.TAG_ESCAPED }}
          MAX_REPLICAS: '4'
          MIN_REPLICAS: '2'
          UTILISATION_AVERAGE_PERCENT: '75'

      - name: Install IBM Cloud CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud --version
          ibmcloud config --check-version=false
          ibmcloud plugin install -f kubernetes-service
          ibmcloud plugin install -f container-registry
      - name: Login to IBM
        run: |
          ibmcloud login -a "${{ secrets.IBM_CLOUD_API_ENDPOINT}}" -r "${{ secrets.IBM_CLOUD_REGION}}" --apikey "${{ secrets.IBM_CLOUD_API_KEY }}"
          echo 'logged in to IBM'
      - name: Configure Cluster
        run: |
          ibmcloud ks cluster config --cluster "${{ secrets.IBM_CLOUD_K8S_CLUSTER_NAME }}"
          echo 'configured cluster'
          sleep 5
      - name: Push image
        run: |
          if ${{ github.event.inputs.delete }} == 'true'
          then
            kubectl --context ${{ secrets.TEST_K8S_CONTEXT }} delete -n ${{ github.event.inputs.deploy_environment }} -k deployment/${{ github.event.inputs.deploy_environment }}
          else
            kubectl --context ${{ secrets.TEST_K8S_CONTEXT }} apply -n ${{ github.event.inputs.deploy_environment }} -k deployment/${{ github.event.inputs.deploy_environment }}
          fi
