name: '- helper (unit testing)'
on: workflow_call

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: '22.12'

      - run: npm install
      - run: npm run build-shared
      - run: npm run test:dev

      - name: Upload Metis Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: appLcovMetisUI
          path: sonar-reports/metis/lcov.info
          if-no-files-found: error

      - name: Upload Sandbox Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: appLcovSandboxUI
          path: sonar-reports/sandbox/lcov.info
          if-no-files-found: error

      - name: Upload Shared Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: appLcovSharedUI
          path: sonar-reports/shared/lcov.info
          if-no-files-found: error
