export const selectorBtnNext = '.next';
export const selectorBtnSubmitData = '[data-e2e="submit-upload"]';
export const selectorBtnSubmitRecord = '[data-e2e="submitRecord"]';
export const selectorBtnSubmitProgress = '[data-e2e="submitProgress"]';
export const selectorBtnSubmitDatasetProblems = '[data-e2e="submitDatasetProblems"]';
export const selectorBtnSubmitRecordProblems = '[data-e2e="submitRecordProblems"]';
export const selectorErrors = '.errors';
export const selectorInputName = '#name';
export const selectorInputCountry = '#country';
export const selectorInputHarvestUrl = '#harvest-url';
export const selectorInputLanguage = '#language';
export const selectorInputMedia = '.record-report input[type="number"]';
export const selectorInputMetadataFormat = '#metadata-format';
export const selectorInputRecordId = '[data-e2e="recordToTrack"]';
export const selectorInputDatasetId = '[data-e2e="datasetToTrack"]';
export const selectorInputUrl = '#url';
export const selectorInputXSLFile = 'form > .form-group:not(.protocol-wrapper) .file-upload';
export const selectorInputZipFile = '.form-group:nth-child(4) .file-upload';
export const selectorLinkDatasetForm = '[data-e2e="link-dataset-form"]';
export const selectorLinkProgressForm = '[data-e2e="link-progress-form"]';
export const selectorProgressOrb = '.nav-orb.progress-orb';
export const selectorReportOrb = '.nav-orb.report-orb';
export const selectorPatternProblemsDatasetOrb = 'li:nth-child(4) .nav-orb.problem-orb';
export const selectorPatternProblemsRecordOrb = 'li:nth-child(6) .nav-orb.problem-orb';
export const selectorUploadOrb = '.nav-orb.upload-orb';
export const selectorProgressTitle = '.dataset-name';
export const selectorSendXSLT = '.form-group:nth-child(6) .checkbox';
